### ISSUE TITLE
Moar boards

### ISSUE THREAD

**Issue by FSund** [diimdeep/awesome-split-keyboards#2]
Here are some more boards/prototypes you might consider adding

Atreis
https://github.com/dekonnection/atreis
https://www.reddit.com/r/MechanicalKeyboards/comments/8gt4cj/photos_the_atreis_an_unsplitted_iris/

Pteron
https://github.com/FSund/pteron-keyboard
https://www.reddit.com/r/MechanicalKeyboards/comments/9blobs/the_pteron/

**Comment by diimdeep** [comment]
Thanks!
