### ISSUE TITLE
Add GoldTouch V2

### ISSUE THREAD

**Issue by mleonhard** [diimdeep/awesome-split-keyboards#42]
Nice list of manufactured and DIY ergo keyboards.  I tried several manufactured keyboards and liked the GoldTouch V2.  I've been using it for about 7 years.

https://www.goldtouch.com/ergonomic-keyboards/

**Comment by diimdeep** [comment]
Added.

**Comment by mleonhard** [comment]
It looks like "Goldtouch Go!2" was added instead of the V2.  The Go!2 is a travel keyboard.  It is not an awesome keyboard.

The Goldtouch V2 is a different keyboard.  The V2 is a sturdy desktop keyboard with excellent key action.  The V2 is an awesome keyboard.  It is excellent for daily use.
