### ISSUE TITLE
Merge top and bottom lists, put images in table

### ISSUE THREAD

**Issue by yourfate** [diimdeep/awesome-split-keyboards#9]
I think we should unify the format by putting all the keyboards in one table, maybe add the pictures in the table, like they did here: https://github.com/BenRoe/awesome-mechanical-keyboard.

Also, the date column, is that the date the repo was first created, or when it was added here?

We should discuss this first though.

**Comment by diimdeep** [comment]
Hi I would like to keep this list and pictures in current gallery like format and to keep table separate like wikipedia style lists.
